### ISSUE TITLE
Doubt about Open Source Development

### ISSUE THREAD

**Issue by ricardopcj** [FezVrasta/ama#14]
Hello FezV, i'm Ricardo and i have a question for you. To begin, i'm sorry if i type something wrong, english is not my primary language.
The question is: what do you recommendo to start in open source dev?
I'm a JS dev and i admire your work on Popper.js and i really want to contribute on any JS library, but when do i open the github repo i get absolutely lost. I  don't mind to start small, maybe some simple project or recreating something than already exist.

Thanks for your atention

**Comment by FezVrasta** [comment]
Hi, I'd suggest to find a project you like and start contributing to it.

It can be anything, documentation changes, small fixes, support on the issue tracker. Slowly you'll gain confidence with the project.
