### ISSUE TITLE
Hi @FezVrasta, I would like to ask for some help with @float-ui/react-dom-interaction. I am trying to create a select but the example I have found has grouped option, however I am failed to modify it to work without the groups. I will be very grateful for your help, thank you.

### ISSUE THREAD

**Issue by SamuelMabonga** [FezVrasta/ama#15]
Hi @FezVrasta, I would like to ask for some help with @float-ui/react-dom-interaction. I am trying to create a select but the example I have found has grouped option, however I am failed to modify it to work without the groups. I will be very grateful for your help, thank you.

**Comment by FezVrasta** [comment]
Hi, the floating-ui repository has a community where anybody can ask questions and get answers from the rest of the members, may I suggest to ask your question there?
