### ISSUE TITLE
Phishing scam using your code

### ISSUE THREAD

**Issue by gnmrc22** [FezVrasta/ama#18]
Hi @FezVrasta, I'd like to ask you if you'd ever hep another Italian take down a black hat hacker who used some of your code for a simple but effective phishing scam who has ruined a small company. I can prove everything.

**Comment by FezVrasta** [comment]
I'm not sure what you are talking about? Care to elaborate?

**Comment by gnmrc22** [comment]
Absolutely. Today a small company named Kimera Automobili got hacked via a phishing scam that was using a website. This website was made by a Turkish computer engineer that used your code as well. 
<img width="1416" alt="SCR-20241021-lfov" src="https://github.com/user-attachments/assets/f31fbb7d-6502-44d8-80e4-907270a69dde">
<img width="1854" alt="SCR-20241021-lfto" src="https://github.com/user-attachments/assets/6403b2de-da6a-4269-bafa-2006aa90afb8">
<img width="1829" alt="SCR-20241021-lfxk" src="https://github.com/user-attachments/assets/043d70fe-a5d9-41b3-9511-adea18f8ef22">
Here you can see the code from his website, clearly containing a program of yours. The owner of this website proceeded to steal all of the information of this small company. 

He's using a code obfuscator as you can see, and I'm asking for your help and expertise to track him down. He looks like a beginner but I'd love to get your feedback as well.

**Comment by gnmrc22** [comment]
The only information I have of the scammer is that he's a Turkish national.

**Comment by FezVrasta** [comment]
I'm sorry. I'm unable to help. I released a lot of open source code that can be freely used by anyone. It doesn't mean I am connected to the people behind this scam.

To give you an idea, my open source code is used by approximately 80% of the websites worldwide.

**Comment by gnmrc22** [comment]
I know Fede, I know. I'm not writing to you to put any blame on your work, it would be insane. I'm asking for your help: I've always battled against black hats and today one of them targeted a company I love. Could you help me in trying to take him down? This is what I'm asking.

**Comment by gnmrc22** [comment]
I'd love to get some help in deobfuscating his HTML code, which he obfuscated using [this tool](https://www.phpkobo.com/deobfuscation-service). Do you know about any countermeasure for it?

**Comment by FezVrasta** [comment]
Unfortunately I have no knowledge on this kind of security matters. I'm unable to help.
