### ISSUE TITLE
Collapsible side nav using bootstrao material design

### ISSUE THREAD

**Issue by codeandcloud** [FezVrasta/ama#2]
Hi @FezVrasta, 

Thank you for the wonderful plugin. bootstrap-material-design.

I want to mimic something like this: http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/

Dont get me wrong. All I want is to get a simple minimalist design like http://rosskevin.github.io/bootstrap-material-design/examples/drawer/ where there is one more feature that collapses the sidebar while clicking / resizing.

I see that you have co-authored both the sites too. Do you have a minimal viable sample?  
Or any pointers to help us with?

**Comment by FezVrasta** [comment]
Hi, the source code of that dashboard is available here:
https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev/docs/examples/dashboard
