### ISSUE TITLE
Source Map for popper.min.js

### ISSUE THREAD

**Issue by cdoole** [FezVrasta/ama#8]
Hi @FezVrasta, I'd like to ask you... 
Do you have a source Map for popper.min.js? I am still learning but I like to keep my project loading time fast. My reason for asking is because I'm using bootstrap 4 to make a portfolio site and they require popperJS could you provide a source map for the minified version or tell me where to go to create my own with the uncompiled version? Any help would be appreciated

**Comment by FezVrasta** [comment]
Here it is

https://unpkg.com/popper.js@1.14.3/dist/popper.min.js.map
